### PR TITLE
added -m/-metricsFile flag to output duplication metrics

### PR DESCRIPTION
**Pull request by dakl**
I decided to patch it myself. I'm not too familiar with C++ so I've basically imitated how the other files are opened, written to and closed. Example output: 

```
TOTAL_READS  DISCORDANT_READ_PAIRS  SPLIT_READS  UNMAPPED_READS  UNMATED_READS  DUPLICATE_READS  PCT_DUPLICATE_READS
4596         0                      0            0               0              1229             26.74
```

cheers

### CODE REVIEW

**Comment by dakl** [comment]
Is this interesting to you? I think it's useful for many users.

**Comment by dakl** [comment]
BUMP

**Comment by marcelm** [comment]
I would be interested in this as well.

**Comment by dakl** [comment]
Hello?

**Comment by ewels** [comment]
+1 for this feature..

**Comment by dakl** [comment]
I'm gonna close this, since it's been four years without a response.

**Pull request closed without merging**
